[package]
name = "indexer-message-sidecar"
version = "0.1.0"
edition = "2024"

[dependencies]
# === Async + Runtime Dependencies === #
tokio = { workspace = true, features = ["full"] }

# === AWS Dependencies === #
aws-config = { version = "1.1.4", features = ["behavior-version-latest"] }
aws-sdk-sqs = "1.50.0"

# === HTTP === #
warp = { version = "0.4", features = ["server"] }
reqwest = { workspace = true }
http = { workspace = true }

# === Workspace Dependencies === #
config = { workspace = true }
task-driver = { workspace = true }

# === Serde === #
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# === Misc Dependencies === #
url = "2.4"
clap = { version = "4", features = ["derive"] }
tracing = { workspace = true }
eyre = { workspace = true }
thiserror = { workspace = true }
uuid = { version = "1.0", features = ["serde"] }
