
###############
### Relayer ###
###############

[services.arbitrum-sepolia-relayer]
[services.arbitrum-sepolia-relayer.build]
dockerfile = "docker/release/Dockerfile"
ecr_repo = "relayer-arbitrum-sepolia-v2"
cargo_features = "default"

[services.arbitrum-sepolia-relayer.deploy]
environment = "arbitrum-sepolia-v2"
resource = "relayer"
cluster_name_override = "arbitrum-sepolia-v2-relayer"
service_name_override = "arbitrum-sepolia-v2-relayer-service"

[services.arbitrum-one-relayer]
[services.arbitrum-one-relayer.build]
dockerfile = "docker/release/Dockerfile"
ecr_repo = "relayer-arbitrum-one-v2"
cargo_features = "default"

[services.arbitrum-one-relayer.deploy]
environment = "arbitrum-one-v2"
resource = "relayer"
cluster_name_override = "arbitrum-one-v2-relayer"
service_name_override = "arbitrum-one-v2-relayer-service"

[services.base-sepolia-relayer]
[services.base-sepolia-relayer.build]
dockerfile = "docker/release/Dockerfile"
ecr_repo = "relayer-base-sepolia-v2"
cargo_features = "default"

[services.base-sepolia-relayer.deploy]
environment = "base-sepolia-v2"
resource = "relayer"
cluster_name_override = "base-sepolia-v2-relayer"
service_name_override = "base-sepolia-v2-relayer-service"

[services.base-mainnet-relayer]
[services.base-mainnet-relayer.build]
dockerfile = "docker/release/Dockerfile"
ecr_repo = "relayer-base-mainnet-v2"
cargo_features = "default"

[services.base-mainnet-relayer.deploy]
environment = "base-mainnet-v2"
resource = "relayer"
cluster_name_override = "base-mainnet-v2-relayer"
service_name_override = "base-mainnet-v2-relayer-service"

[services.ethereum-sepolia-relayer]
[services.ethereum-sepolia-relayer.build]
dockerfile = "docker/release/Dockerfile"
ecr_repo = "relayer-ethereum-sepolia-v2"
cargo_features = "default"

[services.ethereum-sepolia-relayer.deploy]
environment = "ethereum-sepolia"
resource = "relayer"
cluster_name_override = "ethereum-sepolia-relayer"
service_name_override = "ethereum-sepolia-relayer-service"

[services.ethereum-mainnet-relayer]
[services.ethereum-mainnet-relayer.build]
dockerfile = "docker/release/Dockerfile"
ecr_repo = "relayer-ethereum-mainnet-v2"
cargo_features = "default"

[services.ethereum-mainnet-relayer.deploy]
environment = "ethereum-mainnet"
resource = "relayer"
cluster_name_override = "ethereum-mainnet-relayer"
service_name_override = "ethereum-mainnet-relayer-service"
