[package]
name = "types-gossip"
version = "0.1.0"
edition = "2024"

[features]
default = []
mocks = ["dep:constants", "dep:rand", "dep:uuid"]
rkyv = ["dep:rkyv", "dep:darkpool-types"]

[dependencies]
# === Cryptography === #
base64 = { version = "0.22" }
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
rand_core = { workspace = true }

# === Networking === #
libp2p = { workspace = true }
libp2p-identity = { workspace = true }

# === Serialization === #
derivative = "2.2"
rkyv = { workspace = true, optional = true, features = ["uuid-1"] }
serde = { workspace = true }
serde_json = { workspace = true }

# === Workspace Dependencies === #
circuit-types = { workspace = true }
darkpool-types = { workspace = true, optional = true, features = ["rkyv"] }
types-account = { workspace = true }
util = { workspace = true, features = ["networking", "errors"] }

# === Optional === #
constants = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
uuid = { version = "1.1.2", features = ["v4", "serde"], optional = true }
