[package]
name = "renegade-metrics"
version = "0.1.0"
edition = "2024"

[dependencies]
# === Telemetry === #
tracing = { workspace = true }
metrics = { workspace = true }

# === Cryptography / Arithmetic === #
alloy-primitives = { workspace = true }
atomic_float = "1"

# === Workspace Dependencies === #
darkpool-types = { workspace = true }
types-core = { workspace = true }
util = { workspace = true }

# === Misc === #
lazy_static = { workspace = true }
