[package]
name = "task-driver"
version = "0.1.0"
edition = "2024"

[features]
integration = [
    "types-account/mocks",
    "types-tasks/mocks",
    "darkpool-client/integration",
    "state/mocks",
    "test-helpers/blockchain",
    "util/mocks",
]

[[test]]
name = "integration"
path = "integration/main.rs"
harness = false
required-features = ["integration"]

[dependencies]
# === Async + Runtime === #
async-trait = { workspace = true }
crossbeam = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }

# === Cryptography === #
ark-mpc = { workspace = true }
num-bigint = { workspace = true }

# === Ethereum === #
alloy = { workspace = true }

# === Workspace Dependencies === #
darkpool-client = { workspace = true }
darkpool-types = { workspace = true }
circuits-core = { workspace = true, features = ["test_helpers"] }
circuit-types = { workspace = true }
types-core = { workspace = true }
types-gossip = { workspace = true }
types-tasks = { workspace = true }
types-account = { workspace = true }
types-proofs = { workspace = true }
types-runtime = { workspace = true }
constants = { workspace = true }
external-api = { workspace = true, features = ["auth"] }
gossip-api = { workspace = true }
job-types = { workspace = true }
matching-engine-core = { workspace = true }
crypto = { workspace = true }
state = { workspace = true }
system-bus = { workspace = true }
util = { workspace = true }
renegade-metrics = { workspace = true }
renegade-solidity-abi = { workspace = true }

# === HTTP === #
http = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
url = "2"

# === Misc Dependencies === #
itertools = "0.11"
eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { version = "1.1.2", features = ["v4", "serde"] }
metrics = { workspace = true }

[dev-dependencies]
alloy-primitives = { workspace = true }

clap = { version = "4.0", features = ["derive"] }
colored = "2"
config = { workspace = true }
darkpool-client = { workspace = true }
eyre = { workspace = true }
flate2 = "1.0"
inventory = "0.3"

lazy_static = { workspace = true }
mock-node = { workspace = true }
num-traits = "0.2"

rand = { workspace = true }
state = { workspace = true, features = ["mocks"] }
test-helpers = { workspace = true }
util = { workspace = true, features = [
    "blockchain",
    "concurrency",
    "telemetry",
] }

proof-manager = { workspace = true, features = ["mocks"] }
