[package]
name = "system-bus"
version = "0.1.0"
edition = "2024"

[dependencies]
# === Threading Model + Runtime === #
bus = { version = "2.3" }
futures = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }

# === Workspace Dependencies === #
circuit-types = { workspace = true }
darkpool-types = { workspace = true }
types-core = { workspace = true }
types-gossip = { workspace = true }
types-tasks = { workspace = true }
types-wallet = { workspace = true }
types-runtime = { workspace = true }
external-api = { workspace = true, features = ["task-api"] }

# === Misc Dependencies === #
uuid = { version = "1.1.2", features = ["v4", "serde"] }

[dev-dependencies]
rand = "0.8"
