[package]
name = "types-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
hmac = []
rkyv = ["dep:rkyv", "darkpool-types/rkyv"]

[dependencies]
# === Core Dependencies === #
alloy = { workspace = true }
bimap = "0.6.2"
num-bigint = { workspace = true }
serde = { workspace = true }
uuid = { version = "1.1.2", features = ["v4", "serde"] }

# === Workspace Dependencies === #
circuit-types = { workspace = true }
constants = { workspace = true, default-features = false }
darkpool-types = { workspace = true }
util = { workspace = true, features = ["hex-core", "serde", "concurrency"] }

# === HMAC Dependencies === #
base64 = { version = "0.22" }
hmac = "0.12"
rand = { workspace = true }
sha2 = { version = "0.10", features = ["asm"] }

# === Optional === #
rkyv = { workspace = true, optional = true, features = ["std", "alloc"] }
