[package]
name = "external-api"
version = "0.1.0"
edition = "2024"

[features]
default = ["full-api"]
auth = ["dep:http", "dep:thiserror", "types-core/hmac"]
external-match-api = []
admin-api = []
task-api = []
websocket = ["admin-api"]
full-api = [
    "external-match-api",
    "admin-api",
    "task-api",
    "websocket",
    "darkpool-types/proof-system-types",
    "dep:renegade-solidity-abi",
]

[dependencies]
# === Arithmetic === #
num-bigint = { workspace = true }

# === Auth Dependencies === #
http = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }

# === Workspace Dependencies === #
circuit-types = { workspace = true }
darkpool-types = { workspace = true }
types-core = { workspace = true }
types-gossip = { workspace = true }
types-account = { workspace = true }
types-runtime = { workspace = true }
constants = { workspace = true }
crypto = { workspace = true }
util = { workspace = true, features = ["hex"] }
renegade-solidity-abi = { workspace = true, optional = true }

# === Misc Dependencies === #
alloy = { workspace = true }
base64 = "0.22.1"
hex = "0.4"
itertools = { workspace = true }
num-traits = "0.2.15"
serde = { workspace = true }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
uuid = { version = "1.1.2", features = ["v4", "serde"] }

[dev-dependencies]
rand = "0.8.5"
num-traits = "0.2.15"
constants = { workspace = true }
