[package]
name = "types-tasks"
version = "0.1.0"
edition = "2024"

[features]
default = []
mocks = ["types-account/mocks"]
rkyv = ["dep:rkyv"]

[dependencies]
alloy = { workspace = true }

# === Serialization === #
rkyv = { workspace = true, features = ["uuid-1"], optional = true }
serde = { workspace = true }
uuid = { version = "1.1.2", features = ["v4", "serde"] }

# === Workspace Dependencies === #
circuit-types = { workspace = true }
darkpool-types = { workspace = true }
types-account = { workspace = true }
types-core = { workspace = true }
util = { workspace = true, features = ["telemetry"] }
renegade-solidity-abi = { workspace = true }
