[package]
name = "types-tasks"
version = "0.1.0"
edition = "2024"

[features]
default = []
mocks = ["types-account/mocks"]
rkyv = ["dep:rkyv"]

[dependencies]
rkyv = { workspace = true, features = ["uuid-1"], optional = true }
serde = { workspace = true }
uuid = { version = "1.1.2", features = ["v4", "serde"] }

# === Workspace Dependencies === #
types-account = { workspace = true }
types-core = { workspace = true }
util = { workspace = true, features = ["telemetry"] }
