[package]
name = "proof-manager"
version = "0.1.0"
edition = "2024"

[features]
mocks = ["types-account/mocks", "types-proofs/mocks"]

[dependencies]
# === Cryptography === #
ark-mpc = { workspace = true }
mpc-plonk = { workspace = true }

# === Runtime + Threading === #
async-trait = { workspace = true }
crossbeam = { workspace = true }
rayon = { version = "1.5.3" }
tokio = { workspace = true }

# === External Service Client === #
http-auth-basic = "0.3"
reqwest = { version = "0.12.10", features = ["json"] }
serde_json = { workspace = true }

# === Workspace Dependencies === #
circuits-core = { workspace = true, features = ["test_helpers"] }
circuit-types = { workspace = true, features = ["proof-system-types"] }
types-core = { workspace = true }
types-proofs = { workspace = true }
types-tasks = { workspace = true }
types-account = { workspace = true }
types-runtime = { workspace = true }
constants = { workspace = true }
job-types = { workspace = true }
renegade-metrics = { workspace = true }
util = { workspace = true }

# === Misc Dependencies === #
serde = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
