[package]
name = "circuits-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
test_helpers = ["dep:ctor", "util/mocks", "util/matching-engine"]
stats = ["ark-mpc/stats"]
ci = ["test_helpers"]

[[test]]
name = "integration"
path = "integration/main.rs"
harness = false
required-features = ["test_helpers"]

#####################
### Benchmarks ###
#####################

[[bench]]
name = "valid_deposit"
path = "benches/valid_deposit.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "valid_balance_create"
path = "benches/valid_balance_create.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "valid_withdrawal"
path = "benches/valid_withdrawal.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "valid_private_protocol_fee_payment"
path = "benches/valid_private_protocol_fee_payment.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "valid_private_relayer_fee_payment"
path = "benches/valid_private_relayer_fee_payment.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "valid_public_protocol_fee_payment"
path = "benches/valid_public_protocol_fee_payment.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "valid_public_relayer_fee_payment"
path = "benches/valid_public_relayer_fee_payment.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "valid_note_redemption"
path = "benches/valid_note_redemption.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "intent_only_first_fill"
path = "benches/intent_only_first_fill.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "intent_only"
path = "benches/intent_only.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "intent_only_public_settlement"
path = "benches/intent_only_public_settlement.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "intent_only_bounded_settlement"
path = "benches/intent_only_bounded_settlement.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "intent_and_balance"
path = "benches/intent_and_balance.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "intent_and_balance_first_fill"
path = "benches/intent_and_balance_first_fill.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "intent_and_balance_public_settlement"
path = "benches/intent_and_balance_public_settlement.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "intent_and_balance_private_settlement"
path = "benches/intent_and_balance_private_settlement.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "intent_and_balance_bounded_settlement"
path = "benches/intent_and_balance_bounded_settlement.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "output_balance"
path = "benches/output_balance.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "new_output_balance"
path = "benches/new_output_balance.rs"
harness = false
required-features = ["test_helpers"]

[[bench]]
name = "valid_order_cancellation"
path = "benches/valid_order_cancellation.rs"
harness = false
required-features = ["test_helpers"]

[dependencies]
# === Cryptography + Arithmetic === #
alloy-primitives = { workspace = true }
ark-crypto-primitives = { version = "0.4", features = [
    "crh",
    "merkle_tree",
    "sponge",
] }
ark-ec = "0.4"
ark-ff = "0.4"
ark-mpc = { workspace = true }
bigdecimal = "0.3"
jf-primitives = { workspace = true, features = ["parallel", "std"] }
mpc-plonk = { workspace = true, features = ["std"] }
mpc-relation = { workspace = true, features = ["std"] }
num-bigint = { version = "0.4", features = ["rand", "serde"] }
num-integer = "0.1"

# === Workspace Dependencies === #
circuit-macros = { workspace = true }
circuit-types = { workspace = true, default-features = false, features = [
    "proof-system-types",
] }
constants = { workspace = true, features = ["mpc-types"] }
crypto = { workspace = true, features = ["fields", "hash"] }
darkpool-types = { workspace = true, default-features = false, features = [
    "proof-system-types",
] }
util = { workspace = true, features = ["blockchain"] }

# === Misc Dependencies === #
bitvec = "1.0"
ctor = { version = "0.1", optional = true }
futures = { workspace = true }
itertools = "0.10"
lazy_static = { workspace = true }
rand = { version = "0.8" }
serde = { workspace = true, features = ["serde_derive"] }
serde_json = "1.0"

[dev-dependencies]
ark-ec = "0.4"
circuit-types = { workspace = true, features = ["test-helpers"] }
clap = { version = "4.0", features = ["derive"] }
colored = "2"
criterion = { version = "0.5", features = ["async", "async_tokio"] }
ctor = "0.1"
dns-lookup = "1.0"
eyre = { workspace = true }
inventory = "0.3"
k256 = "0.13"
mpc-plonk = { workspace = true, features = ["test_apis", "std"] }
rand = "0.8"
serde_json = "1.0"
test-helpers = { workspace = true, features = ["mpc-network", "test-harness"] }
tokio = { version = "1.12", features = ["macros", "rt-multi-thread"] }
util = { workspace = true, features = [
    "mocks",
    "matching-engine",
    "telemetry",
] }
